# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.TextField(max_length=8000)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='images/placeholder.png', upload_to='images')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
    ]
